coverage:
  status:
    project:
      default:
        threshold: 0.10%
      webservice-go/backend:
        target: auto
        flags: [ webservice_backend ]
      webservice-go/frontend:
        target: auto
        flags: [ webservice_frontend ]

flags:
  webservice_backend:
    paths: [ ./coverage.out ]
    carryforward: true
  webservice_frontend:
    paths: [ ./web/app/coverage/coverage-final.json ]
    carryforward: true

