
app = 'blocky-chihuahua-galaxy'
primary_region = 'cdg'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[[vm]]
  size = 'shared-cpu-1x'
  memory = "256mb"

[[services]]
  auto_start_machines = false
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[metrics]
  port = 4000
  path = "/metrics"
