dist:
  name: otelcol-custom-dev  # Set To whatever for development, will be overrided by Nix derivation
  description: Local OpenTelemetry Collector binary
  output_path: /tmp/dist

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.88.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.88.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.88.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.88.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
  - gomod: github.com/clement-casse/Playground/otelcol-custom/exporter/cyphergraphexporter 47c4f641ce700ca5adf0def79c2c68739e99e53c

# extensions:
#   - gomod: 