run:
  timeout: 3m
  concurrency: 4
  skip-dirs:
    - vendor

linters-settings:
  depguard:
    rules:
      main:
        files: [ $all, "!$test" ]
        allow:
          - $gostd
          # Block warning import 'tailscale.com/client/tailscale' is not allowed from list 'Main' (depguard)
          # because I do intentionnaly want to import this unstable library
          - tailscale.com/client/tailscale
  errcheck:
    exclude-functions:
      # os.Stdout.WriteString("...") and os.Stderr.WriteString("...") are used as logger for traefik plugin
      - (*os.File).WriteString
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/clement-casse/playground/traefik-plugin-tailscale-auth
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - varnamelen
    - exhaustruct
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - exhaustivestruct
    - goerr113
    - wrapcheck
    - ifshort
    - noctx
    - lll
    - gomnd
    - forbidigo

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - text: "G104:" # Duplicated from errcheck checks
      linters:
        - gosec
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot