name: "Traefik TS Auth Plugin"
on:
  pull_request:
    paths:
      - "traefik-plugin-tailscale-auth/**/*.go"
      - "traefik-plugin-tailscale-auth/go.*"
  push:
    branches:
      - 'main'
    paths:
      - "traefik-plugin-tailscale-auth/**"

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  GO_VERSION: "~1.21"

defaults:
  run:
    working-directory: traefik-plugin-tailscale-auth

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Go Vet
        run: go vet -json ./...
      - name: Go fmt
        run: test -z $(go fmt ./...)
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          skip-pkg-cache: true
          working-directory: traefik-plugin-tailscale-auth
