name: "webservice-go/frontend"
on:
  pull_request:
    paths:
      - "webservice-go/web/app/**"
  push:
    branches:
      - 'main'
    paths:
      - "webservice-go/**"

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  NODE_VERSION: "20"

defaults:
  run:
    working-directory: webservice-go/web/app

jobs:
  Validate-Front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: "webservice-go/web/app/package-lock.json"
      - name: NPM clean install
        run: npm clean-install
      - name: Lint
        run: npm run lint

  Test-Front:
    runs-on: ubuntu-latest
    needs: Validate-Front
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: "webservice-go/web/app/package-lock.json"
      - name: NPM clean install
        run: npm clean-install
      - name: Execute tests
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: ./codecov.yaml
          flags: webservice-front
