schema = 3

[mod]
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.5.2"
    hash = "sha256-g+kEivzu+sIaO5fDGR4RCpm3LmJSzmsAO16wAzBnP6c="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v0.0.0-20221026131551-cf6655e29de4"
    hash = "sha256-2fwUAhc8vXeOMKQrX4wIS+t3tLKxpRQ9d/tWsakxsYk="
  [mod."github.com/acomagu/bufpipe"]
    version = "v1.0.3"
    hash = "sha256-hIQf2lqZZv4dN8JwRyhNoBjStL9Mgih6f7Hy8RDU5Kg="
  [mod."github.com/aead/chacha20"]
    version = "v0.0.0-20180709150244-8b13a72661da"
    hash = "sha256-2ZTtI0mvOD6oK41tf3C4G+/1JaH4lK109qviNQt+dT0="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-SuFgpvp7KGO4f2t0KnkhSUv7iRI7oGq40CjRc1tLNr4="
  [mod."github.com/apparentlymart/go-textseg/v13"]
    version = "v13.0.0"
    hash = "sha256-Hn+zO0J/vnG5U6JvZfRyWm8vsqYdjh4RAreWnZLCQKQ="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/blang/semver"]
    version = "v3.5.1+incompatible"
    hash = "sha256-vmoIH5J0esVFmLDT2ecwtalvJqRRoLwomysyvlIRmo8="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.16.1"
    hash = "sha256-Z/H2bliHQttBM1mJmY3umFGl+RAcN5MgXpDcr1e/1O4="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.24.2"
    hash = "sha256-UszAKKLThTPegAJxdLJQmt5veVLroC5ww42atVk+SjM="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.7.1"
    hash = "sha256-GdPbyi762tGmU0ASLv76/DDjOubYp6K1kNio/IUVUiQ="
  [mod."github.com/cheggaaa/pb"]
    version = "v1.0.29"
    hash = "sha256-G0LynvELyT0XBFH/Xp4OcTr10OKsV3/K6sHNEyz4gn8="
  [mod."github.com/cloudflare/circl"]
    version = "v1.3.3"
    hash = "sha256-ItdVkU53Ep01553/tJ4MdAwoTpPljRxiBW9sAd7p0xI="
  [mod."github.com/containerd/console"]
    version = "v1.0.4-0.20230313162750-1ae8d489ac81"
    hash = "sha256-Qus81DgpWHJ6RRqeKOKcUFvzCxvPzygJqBabvBsBuHU="
  [mod."github.com/djherbis/times"]
    version = "v1.5.0"
    hash = "sha256-3i0MAv5bCzAJ3zriOcOHv+rcZwHTm3CFcb64KF8edPc="
  [mod."github.com/emirpasic/gods"]
    version = "v1.18.1"
    hash = "sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.0"
    hash = "sha256-A62eSLI/0y4sfwCsZhe/uoSC9Z3TryyW+PyWIcknYdE="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.4.0"
    hash = "sha256-u4PSYgjhzca0uPY5n4ZPQEGSzU3rs56A4EGu7nskFEY="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.6.0"
    hash = "sha256-b3EyjQ4owJwSRVHAUw84unvkB0vt6p7vDY90u549n64="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/glog"]
    version = "v1.1.0"
    hash = "sha256-FgkBzn32nsq5Fpz0KKOrOqKap6pa2A1P3N2C0/Qp820="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/grpc-ecosystem/grpc-opentracing"]
    version = "v0.0.0-20180507213350-8e809c8a8645"
    hash = "sha256-vNuUuD7/hTVrZMR4VN2YpIh7Os+6eDHsMLHe2GB/4/s="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.16.1"
    hash = "sha256-EhFrohg76g/FYixjr8yaWoHqugOdV8EL2utbgjdU0fA="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.1"
    hash = "sha256-ZTP9pLgwAAvHYK5A4PqwWCHGt00x5zMSOpCPoomQ3Sg="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.2.0"
    hash = "sha256-Ta7ZOmyX8gG5tzWbY2oES70EJPfI90U7CIJS9EAce0s="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.18"
    hash = "sha256-QpIn0DSggtBn2ocyj0RlXDKLK5F5KZG1/ogzrqBCjF8="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v0.0.0-20150314170334-ad45545899c7"
    hash = "sha256-aR+xW4TnVo96Cbw168fhdIBEh7O43mOlHdLx/WxrwVs="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20211018074035-2e021307bc4b"
    hash = "sha256-v4zQmLl5Z6hoKtuH0Ry6hRwAKNWna4rXirK62LXNvbY="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.1"
    hash = "sha256-vbltynBfzDXd+XO/naRmAeh71o8jlT7Y4fHA1Jj6qg8="
  [mod."github.com/opentracing/basictracer-go"]
    version = "v1.1.0"
    hash = "sha256-VU1bU8eTMgPt0O0wLR4dJ4dDN1Yb8XiJjbEPvUuOCBk="
  [mod."github.com/opentracing/opentracing-go"]
    version = "v1.2.0"
    hash = "sha256-kKTKFGXOsCF6QdVzI++GgaRzv2W+kWq5uDXOJChvLxM="
  [mod."github.com/pjbgf/sha1cd"]
    version = "v0.3.0"
    hash = "sha256-kX9BdLh2dxtGNaDvc24NORO+C0AZ7JzbrXrtecCdB7w="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/term"]
    version = "v1.1.0"
    hash = "sha256-4zgH0pWzCb8f/98ACk+GPF1D5iFBjzr+Ybjsb4qQnjo="
  [mod."github.com/pulumi/pulumi-kubernetes/sdk/v4"]
    version = "v4.2.0"
    hash = "sha256-Fw1tTdDyDBWViMdMrgJh3vAiZx1l42Z4vBG9KSfn6Sw="
  [mod."github.com/pulumi/pulumi/sdk/v3"]
    version = "v3.84.0"
    hash = "sha256-4olEYkQwJ57uRlWprJJgzyAXCZY0p6NFfAfVfh4JUKc="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.4"
    hash = "sha256-B8tbL9K6ICLdm0lEhs9+h4cpjAfvFtNiFMGvQZmw0bM="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.9.0"
    hash = "sha256-XKmbu8l55XGrvC20j8jocpauwZsdbP83YAwH79BEAC4="
  [mod."github.com/sabhiram/go-gitignore"]
    version = "v0.0.0-20210923224102-525f6e181f06"
    hash = "sha256-A1aJFlcPRQvDqdJmEwpzhftR8C1Kzv1hXPszq8eO76Q="
  [mod."github.com/santhosh-tekuri/jsonschema/v5"]
    version = "v5.0.0"
    hash = "sha256-/qj8fikv+vpDVYevZiRL7a6a3n/IO2eEx1q4zECLbjQ="
  [mod."github.com/sergi/go-diff"]
    version = "v1.2.0"
    hash = "sha256-d2higuBRee4ylRuCpPQV5+g0XK5yNQgDpudNor0qD2o="
  [mod."github.com/skeema/knownhosts"]
    version = "v1.1.0"
    hash = "sha256-WpHhJaZea5zh7PBZPuL4a9XJyADeS7TK0DGnQF4NjmI="
  [mod."github.com/spf13/cobra"]
    version = "v1.6.1"
    hash = "sha256-80B5HcYdFisz6QLYkTyka7f9Dr6AfcVyPwp3QChoXwU="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/texttheater/golang-levenshtein"]
    version = "v1.0.1"
    hash = "sha256-WL0Mh5kh6FHYvZQx50yatoW1zUuvxZ4YW4fhk5k+IZM="
  [mod."github.com/tweekmonster/luser"]
    version = "v0.0.0-20161003172636-3fa38070dbd7"
    hash = "sha256-PwxmnTmN3pZXQdZODAxiJ9xvsLQEeuj93bnWKR6Ogeg="
  [mod."github.com/uber/jaeger-client-go"]
    version = "v2.30.0+incompatible"
    hash = "sha256-6s9eX+QOOL0B1T+9hpcQ+rudQpYd9ju/2AEDAaBXopo="
  [mod."github.com/uber/jaeger-lib"]
    version = "v2.4.1+incompatible"
    hash = "sha256-RcnLDfoiYkzUnmQAC2D2/VNGOaOXmiEcfAFcyXph6R8="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.3"
    hash = "sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.12.1"
    hash = "sha256-919kjUlwSvoWgOovoAX8cxKo9Bp5Zx+VMN24pVNjUNU="
  [mod."go.uber.org/atomic"]
    version = "v1.9.0"
    hash = "sha256-D8OtLaViqPShz1w8ijhIHmjw9xVaRu0qD2hXKj63r4Q="
  [mod."golang.org/x/crypto"]
    version = "v0.3.1-0.20221117191849-2c476679df9a"
    hash = "sha256-QvYlV+X+xf3mv00HK+bVbhx07Om8HsnLqDrsYUiSCdY="
  [mod."golang.org/x/net"]
    version = "v0.10.0"
    hash = "sha256-HkGiUYBZOBdOtt7mYo3N3swFjjAXzW++pG2JeWGJR9Q="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.8.0"
    hash = "sha256-wLPPnoFkHM1HPUaFIfRyQZOJjrqXVZimB0nMySly7Xg="
  [mod."golang.org/x/term"]
    version = "v0.8.0"
    hash = "sha256-Dr+sLVwiZZRFCaZ1JsHdQSL1PrpeRGF1zilibyw1XrA="
  [mod."golang.org/x/text"]
    version = "v0.9.0"
    hash = "sha256-tkhDeMsSQZr3jo7vmKehWs3DvWetwXR0IB+DCLbQ4nk="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230706204954-ccb25ca9f130"
    hash = "sha256-xjnUWHd5Hzbv7JBIJaSARxHJJlEMPAL5qDbDDiUzxXo="
  [mod."google.golang.org/grpc"]
    version = "v1.57.0"
    hash = "sha256-hP6alxFu+pcLI4gT3idzEMYNp+DbU3P4xhkpIqGCPXg="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/frand"]
    version = "v1.4.2"
    hash = "sha256-YdLiDKB1l78m55JpoCEw0TrY2vG2EH6zAIM5Sl+QNJM="
  [mod."sourcegraph.com/sourcegraph/appdash"]
    version = "v0.0.0-20211028080628-e2786a622600"
    hash = "sha256-sxLK+576Zjs6rgg6Z2PulncCLwjG6/Au9m6h2rsmzNs="
